title: Richard Flint - RichardFlint.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Richard Flint, blog posting about Java, Javascript, Agile
  and other thoughts about software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://richardflint.co.uk"
disqus: "richardflint"

include:
 - .well-known